name: Gradle Plugin Build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Set version in build.gradle to 23.0
        run: |
          sed -i 's/version = "[^"]*"/version = "23.0"/' build.gradle

      - name: Build with Gradle
        run: ./gradlew build -Pproject.branch=master

      - name: Get correct JAR
        id: jar
        run: |
          mkdir staging
          for file in build/libs/*.jar; do
            if [[ "$(basename "$file")" != *-sources.jar && "$(basename "$file")" != *-javadoc.jar ]]; then
              cp "$file" staging/
              echo "jar_name=$(basename "$file")" >> "$GITHUB_OUTPUT"
              break
            fi
          done

      - name: Upload the .jar directly
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.jar.outputs.jar_name }}
          path: staging/${{ steps.jar.outputs.jar_name }}
          compression-level: 0
